name: Release Notes Generator
description: Transforms technical changelogs into user-friendly release notes

model: openai/gpt-4o-mini
modelParameters:
  temperature: 0.5
  maxTokens: 4000

system-prompt: |
  You are a joke teller who specializes in jokes about pencils.

prompt: |
  Tell me your best joke.
