_extends: .github

repository:

  #─────────────────────────────────────────────────────────────────────────────
  # "About" section (on Home Page)
  #─────────────────────────────────────────────────────────────────────────────

  # A short description of the repo
  # MUST BE A SINGLE LINE
  description: Template repo for publishing NuGet packages

  # A URL with more information about the repo
  homepage:

  # A comma-separated list of topics to set on the repo
  # See https://github.com/topics
  topics: [dotnet, csharp, nuget]

  #─────────────────────────────────────────────────────────────────────────────
  # Settings → General
  # https://github.com/repository-settings/app/blob/master/docs/plugins/repository.md
  # https://docs.github.com/en/rest/repos/repos#update-a-repository
  #─────────────────────────────────────────────────────────────────────────────

  # The name of the repo
  name: .template-NuGet

#───────────────────────────────────────────────────────────────────────────────
# Issues → Labels
# https://github.com/repository-settings/app/blob/master/docs/plugins/labels.md
#───────────────────────────────────────────────────────────────────────────────
labels:

  # Dependabot Ecosystems
  # https://docs.github.com/en/code-security/dependabot/ecosystems-supported-by-dependabot/supported-ecosystems-and-repositories
  # (each uses its own marketing color)

  - name: .NET SDK
    color: "#522ed1"
    description: Updates to the required .NET SDK

  - name: NuGet
    color: "#07497f"
    description: Updates to NuGet packages
