name: .NET Build and Test

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x" # Adjust this to your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test with coverage
        run: dotnet test --no-build --collect:"XPlat Code Coverage" --settings test/Coverlet.runsettings --results-directory coverage

      - name: Generate coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.9
        with:
          reports: "coverage/**/coverage.opencover.xml"
          targetdir: "coveragereport"
          reporttypes: "MarkdownSummary"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: coverage
          path: coveragereport/Summary.md
