#       - name: Generate coverage report
#         uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
#         with:
#           reports: "coverage/**/coverage.opencover.xml"
#           targetdir: "coveragereport"
#           reporttypes: "MarkdownSummary"

#       - name: Add Coverage PR Comment
#         uses: marocchino/sticky-pull-request-comment@v2
#         if: github.event_name == 'pull_request'
#         with:
#           header: coverage
#           path: coveragereport/Summary.md
